name: Deploy to nodejs server

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: a
        run: echo "deploy cicd pipeline executed"
      - name: b
        run: npm run build --if-present
      - name: c
        run: |
          echo "hello"
          echo "he"

      - name: d
        run: echo "use"
